init_param:
    #本番かデモかを指定する。on => 本番、それ以外 => デモ
    production: ""
    # production: "on"
    #取引する通貨ペア　現在は動作に担保がもてませんので、変更しないでください。
    currency_pare: "USD/JPY"
    #一度の取引で購入する金額
    amount: "2000"

high_low_aus:
    #Higl_LowオーストラリアにログインするIDとパスワード
    user_id: ""
    password: ""
    #シグナルがなく取引がないときに画面を操作だけしてアクティブな状態を保つ間隔（分）
    re_init_min_time: "10"
    #購入失敗時、再購入をする時間
    re_buy_sec_time:  "10"

signal:
    #MT4がシグナルファイルを吐き出すフォルダパス
    folder_path: "C:\\Users\\Kinjo.Shogo\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common\\Files"

auto_trading_time: 
    #自動売買を始める時間と終わる時間
    start_time: "08:00"
    end_time: "02:00"

gmail_init:
    #ご自身が使用しているメールアドレス
    mail_address: "shogo14kinjo@gmail.com"
    #事前に取得していたアプリパスワード
    app_password: "zmwetsgkkaogqgoa"